/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/d4870464-d2f0-4b98-a619-41eedb65e5c4 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float metalDetect;
  float pH;
  float tEMP;
  float tURBIDITY;
  bool logDATA;


  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {

   if (Serial.available()) {
    String data = Serial.readStringUntil('\n'); // Read data from Arduino Mega
    handleDataFromMega(data); // Process data from Arduino Mega
  
   }
  ArduinoCloud.update();
  // Your code here 
    
}

void handleDataFromMega(String data) {
  // Parse data received from Arduino Mega and update properties

  float MtD =  data.substring(0, data.indexOf(',')).toFloat();
  data.remove(0, data.indexOf(',') + 1);

  float phValue = data.substring(0, data.indexOf(',')).toFloat();
  data.remove(0, data.indexOf(',') + 1);
  
  float turbidityLevel = data.substring(0, data.indexOf(',')).toFloat();
  data.remove(0, data.indexOf(',') + 1);
  
  float temperature =  data.toFloat();
  

 Serial.println(String(metalDetect) + "," +  String(phValue) + "," + String(turbidityLevel) + "," + String(temperature) );

pH = phValue;
tEMP = temperature;
tURBIDITY = turbidityLevel;
metalDetect = MtD;
}

/*
  Since LogDATA is READ_WRITE variable, onLogDATAChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLogDATAChange()  {
  // Add your code here to act upon LogDATA change
}
