// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "476d0f59-81ba-4128-b148-a10ed26b471e";

const char SSID[]               = "";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "";    // Secret device password

void onLogDATAChange();

float metalDetect;
float pH;
float tEMP;
float tURBIDITY;
bool logDATA;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(metalDetect, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pH, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tEMP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tURBIDITY, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(logDATA, READWRITE, ON_CHANGE, onLogDATAChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);